### ISSUE TITLE
Adding to Flash CC

### ISSUE THREAD

**Issue by ralpanez** [freshplanet/ANE-Google-Play-Game-Services#46]
Hello!

I don't know how to use it correctly. I've added the ANE to my project, then I've added the classes to the project. But now, what I've to do?

When the game finish the loading, I go to the frame 2, the frame 2 has tgis code:

`import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGames;
import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGamesEvent;

this.addEventListener(Event.ENTER_FRAME, loadingLOGIN);

function loadingLOGIN(e: Event): void {
   signIn();
  `
But Flash Outuput says that 'singIn' don't exist. What I have to do to ask user to log in to continue to the game? Thanks!

The app.xml includes this:

`<application xmlns="http://ns.adobe.com/air/application/17.0">
    <id>my.package.id</id>
    <versionNumber>0.0.2</versionNumber>
    <versionLabel/>
    <filename>My Game</filename>
    <description/>
    <name>My Game</name>
    <copyright/>
    <initialWindow>
      <content>Game.swf</content>
      <systemChrome>standard</systemChrome>
      <transparent>false</transparent>
      <visible>true</visible>
      <fullScreen>true</fullScreen>
      <aspectRatio>portrait</aspectRatio>
      <renderMode>cpu</renderMode>
      <autoOrients>false</autoOrients></initialWindow>
    <icon/>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <android>
      <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ MYAPPNUMBER" />
<activity android:name="com.freshplanet.googleplaygames.SignInActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"/>
</manifest>]]></manifestAdditions>
</android>
  <supportedLanguages>es</supportedLanguages>
`

Is correct?

**Comment by ralpanez** [comment]
I modified my code, now I can use the functions, etc. But i have a problem. NOTHING HAPPENS. I think its an XML error. Can someone tell me how I can edit the XML correctly? This is my new XML:

![test](https://cloud.githubusercontent.com/assets/17657543/13555935/e7b5ee94-e3cd-11e5-9198-6dc6fca8a858.png)

**Comment by ralpanez** [comment]
Solved. Now It crashes. Here is the log from Google:

java.lang.NoClassDefFoundError: com.freshplanet.googleplaygames.GameHelper
    at com.freshplanet.googleplaygames.ExtensionContext.createHelperIfNeeded(Unknown Source)
    at com.freshplanet.googleplaygames.SignInActivity.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

anyone?

**Comment by Laur3nt1u** [comment]
you need another ane with google play services in your project, I you have one it's not the right version of gps, you can check my fork (you'll need google play games ane and google play services ane), my version of google play games has a bug when you receive the score from the leaderboard but I will fix it tomorrow

**Comment by ralpanez** [comment]
This?
https://github.com/Laur3nt1u/ANE-Google-Play-Services

**Comment by Laur3nt1u** [comment]
https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services and https://github.com/Laur3nt1u/ANE-Google-Play-Services

**Comment by ralpanez** [comment]
So, the FreshPlanet ane is not working? I have to delete the Freshplanet ANE and introduce these two?

**Comment by ralpanez** [comment]
Well, i've added the new ANE but now when I Click to Publish it says that I have an error in my XML...

I didn't change anything in my XML, only I've added this:

<extensionID>com.laurentiu.AirGooglePlayServices</extensionID>

so:

 <extensions>
    <extensionID>com.freshplanet.AirGooglePlayGamesService</extensionID>
    <extensionID>com.laurentiu.AirGooglePlayServices</extensionID>
  </extensions>

**Comment by Laur3nt1u** [comment]
you don't have to add anything

Actually, where did you added?

**Comment by ralpanez** [comment]
Flash adds automatically to XML the ExtensionID when I add the ANE

**Comment by Laur3nt1u** [comment]
I thought that you added manually. What error did you get?

**Comment by ralpanez** [comment]
This is before I add the ANE:
![before](https://cloud.githubusercontent.com/assets/17657543/13557148/44edafd6-e3ea-11e5-9fb1-b7f163508247.png)
![test2](https://cloud.githubusercontent.com/assets/17657543/13557151/4bb44a28-e3ea-11e5-88da-dea64fdd489c.png)
This is now:
![3](https://cloud.githubusercontent.com/assets/17657543/13557166/810f882c-e3ea-11e5-8052-6e9154258093.png)
![4](https://cloud.githubusercontent.com/assets/17657543/13557182/bcd38db8-e3ea-11e5-8aeb-92de4e92f0d6.png)

![5](https://cloud.githubusercontent.com/assets/17657543/13557170/8909563e-e3ea-11e5-915d-32fee906bc75.png)

**Comment by ralpanez** [comment]
The Adobe Flash Professional error says that the Space of names not valid in the descriptor file of the Application

**Comment by ralpanez** [comment]
That happens when I attach the 2 ANE to the project,if I only attach one I don't have these problem.

**Comment by Laur3nt1u** [comment]
```
    <android>
    <manifestAdditions>
        <![CDATA[<manifest android:installLocation="auto">
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
            <application>
                <activity android:name="com.freshplanet.googleplaygames.SignInActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
                <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ YOUR_APP_ID" />
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
            </application>
        </manifest>]]>
    </manifestAdditions>
  </android>
```

you need to add com.google.android.gms.version as above and I think you have to use air 20 because that's what I used to compile, but use the 20.0.0.204 because I had all sorts of problems with the new ones

**Comment by ralpanez** [comment]
But I'm using Flash Professional CC 2015, the maximum version of air is 17, should I have to update my Flash?

And I try to add to the XML the
`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
 and I can't compile, shows the same error. The error is the 102: Invalid namespace, Check the namespace spelling.

This is my XML:

![xmlllllllllll](https://cloud.githubusercontent.com/assets/17657543/13577036/cdbc951a-e490-11e5-9f63-ecf47ef7429e.png)

If I delete the line, Flash when I Publish, creates the same line because the ane is included in the project.

**Comment by ralpanez** [comment]
![flv](https://cloud.githubusercontent.com/assets/17657543/13577132/40a66bbe-e491-11e5-99bd-32590d17d802.png)
These are my options

**Comment by ralpanez** [comment]
I just update to AIR 20.0, version 20.0.0.260 because is the version from the Adobe Page, I cannot find the SDK for 20.0.0.204, now I can Publish without errors but the game still crashes. I'm sending the updated APK to Google Play to see what's the error.

**Comment by Laur3nt1u** [comment]
Give me your email

**Comment by ralpanez** [comment]
rafabcn1991@gmail.com

**Comment by RuelKim** [comment]
I have same problem too...
can I get the ane file?
xeruel@naver.com

**Comment by ralpanez** [comment]
https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services and https://github.com/Laur3nt1u/ANE-Google-Play-Services you have to add the two ANE to your project.

Hope it helps

**Comment by ralpanez** [comment]
Make sure you are using AIR 20.0 in your project (if you are using Flash)

**Comment by zosime** [comment]
ㅡㅓ쩡ㅇㅊ크웅ㅇㄹㄲㄹ

나의 iPhone에서 보냄
1. 3. 8. 오전 10:07 RuelKim notifications@github.com 작성:

**Comment by swarajcs** [comment]
Hi, 

 am also having issue with adding google play services to my game.

am using the code.

import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGames;
import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGamesEvent;
import com.laurentiu.ane.AirGooglePlayServices.AirGooglePlayServices;

```
        AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_IN_SUCCESS, onSignInSuccess);
        AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_OUT_SUCCESS, onSignOutSuccess);
        AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_IN_FAIL, onSignInFail);
```

stage.addEventListener(MouseEvent.MOUSE_DOWN, launch_app_fn);
function launch_app_fn(event:MouseEvent)
{
    txt.text = "button clicked  ";
    try  
    {  
            //AirGooglePlayGames.getInstance().isSignedIn();
            AirGooglePlayGames.getInstance().signIn(); 

```
}catch(err)
{       txt.text = ""+err;
}
```

}

function onSignInSuccess(event:AirGooglePlayGamesEvent)
{txt.text = "onSignInSuccess ";
}
function onSignOutSuccess(event:AirGooglePlayGamesEvent)
{txt.text = "onSignOutSuccess ";
}
function onSignInFail(event:AirGooglePlayGamesEvent)
{txt.text = "onSignInFail ";
}

it showing error ArgumentError: Error #3500

am using adobe air version 21. Please help me with this issue. Will it only work with version 20 ?
